name = "LocalCoverage"
uuid = "5f6e1e16-694c-5876-87ef-16b5274f298e"
authors = ["Tamas K. Papp <tkpapp@gmail.com>"]
version = "0.3.0"

[deps]
CoverageTools = "c36e975a-824b-4404-a568-ef97ca766997"
DefaultApplication = "3f0dd361-4fe0-5fc6-8523-80b14ec94d85"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
CoverageTools = "1"
DocStringExtensions = "0.8"
PrettyTables = "0.12, 1.0"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
